/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.DaoFrigorifico;
import Model.Frigorifico;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class DialogFrigorifico extends javax.swing.JDialog {
    
    DaoFrigorifico dao = new DaoFrigorifico();
    
    //filtros
    private void carregaFrigorifico(){
        TableFrigorifico.setModel(new MyTableModel( Frigorifico.class, dao.getFrigorificoList(), TableFrigorifico));            
    }
    
    private void carregaFrigorifico(String filtro){
        TableFrigorifico.setModel(new MyTableModel( Frigorifico.class, dao.getFrigorificoList(filtro), TableFrigorifico));    
    }
    
    //INICIAR COMPONENTES
    private void iniciaComponentes(){
        TextID.setText("");
        TextNome.setText("");
        TextCNPJ.setText("");
        TextTelefone.setText("");
        TextEndereco.setText("");
        TextResponsavel.setText("");
        TextPesquisar.setText("");
        TextNome.requestFocus();
    }
    //CRIAR UM OBJETO A PARTIR DA TELA
    private Frigorifico populateObjeto(){
        return(new Frigorifico(TextID.getText().isEmpty() ? 0 : Integer.parseInt(TextID.getText()), TextNome.getText(), TextCNPJ.getText(),TextTelefone.getText(),TextEndereco.getText(),TextResponsavel.getText()));
    }
    //PREENCHER OS COMPONENTES COM UM OBJETO
    private void populateComponente(Frigorifico frigorifico){
        TextID.setText(frigorifico.getId()+""); //"" converte para string nesse caso
        TextNome.setText(frigorifico.getNome());
        TextCNPJ.setText(frigorifico.getCnpj());
        TextTelefone.setText(frigorifico.getTelefone());
        TextEndereco.setText(frigorifico.getEndereco());
        TextResponsavel.setText(frigorifico.getResponsavel());  
    }


    /** Creates new form DialogFrigorifico */
    public DialogFrigorifico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextID = new javax.swing.JTextField();
        TextNome = new javax.swing.JTextField();
        TextEndereco = new javax.swing.JTextField();
        TextResponsavel = new javax.swing.JTextField();
        TextPesquisar = new javax.swing.JTextField();
        ButtonPesquisar = new javax.swing.JButton();
        ButtonNovo = new javax.swing.JButton();
        ButtonSalvar = new javax.swing.JButton();
        ButtonRemover = new javax.swing.JButton();
        TextCNPJ = new javax.swing.JFormattedTextField();
        TextTelefone = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableFrigorifico = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FRIGORIFICO");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CADASATRO DE FRIGORIFICO"));

        jLabel1.setText("CÓDIGO");

        jLabel2.setText("NOME");

        jLabel3.setText("CNPJ");

        jLabel4.setText("ENDERECO");

        jLabel5.setText("TELEFONE");

        jLabel6.setText("RESPONSÁVEL");

        jLabel7.setText("PESQUISAR POR NOME OU CNPJ");

        TextID.setEditable(false);

        ButtonPesquisar.setText("PESQUISAR");
        ButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesquisarActionPerformed(evt);
            }
        });

        ButtonNovo.setText("NOVO");
        ButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNovoActionPerformed(evt);
            }
        });

        ButtonSalvar.setText("SALVAR");
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        ButtonRemover.setText("REMOVER");
        ButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRemoverActionPerformed(evt);
            }
        });

        try {
            TextCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TextTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextID, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextNome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextResponsavel)))
                .addGap(0, 205, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(TextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonPesquisar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(ButtonNovo)
                        .addGap(128, 128, 128)
                        .addComponent(ButtonSalvar)
                        .addGap(137, 137, 137)
                        .addComponent(ButtonRemover)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TextResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPesquisar))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonNovo)
                    .addComponent(ButtonSalvar)
                    .addComponent(ButtonRemover))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TableFrigorifico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableFrigorifico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableFrigorificoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableFrigorifico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            this.carregaFrigorifico();
        }catch(Exception ex){
            System.out.println("ERRO: "+ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void TableFrigorificoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableFrigorificoMouseClicked
        // TODO add your handling code here:
            if (evt.getClickCount()==2){
                String valor= TableFrigorifico.getValueAt(TableFrigorifico.getSelectedRow(),0)+""; //+"" TRANSFORMA EM STRING
                int codigo = Integer.parseInt(valor);
                this.populateComponente(dao.getFrigorifico(codigo));
            }
    }//GEN-LAST:event_TableFrigorificoMouseClicked

    private void ButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNovoActionPerformed
        // TODO add your handling code here:
         this.iniciaComponentes();
    }//GEN-LAST:event_ButtonNovoActionPerformed

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        // TODO add your handling code here:
        //NOME
        try {
            double teste;
            teste = Double.parseDouble(TextNome.getText());
            JOptionPane.showMessageDialog(null, "NÃO É PERMITIDO NÚMEROS NO CAMPO DE NOME");
            TextNome.setText("");
            TextNome.requestFocus();
            return;
        } catch (Exception nome) {
            
        }
        
        if (TextNome.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "CAMPO NOME NÃO PODE SER VAZIO");
            TextNome.requestFocus();
            return;
        }
        
        //CNPJ
        if(TextCNPJ.getText().equals("  .   .   /    -  ")){
            JOptionPane.showMessageDialog(null, "CAMPO CNPJ NÃO PODE SER VAZIO");
            TextCNPJ.setText("");
            TextCNPJ.requestFocus();
            return;
        }
        
        //ENDERECO
        if (TextEndereco.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "CAMPO ENDEREÇO NÃO PODE SER VAZIO");
            TextEndereco.requestFocus();
            return;
        }
        
        //TELEFONE
        if(TextTelefone.getText().equals("(  )       -    ")){
            JOptionPane.showMessageDialog(null, "CAMPO TELEFONE NÃO PODE SER VAZIO");
            TextTelefone.setText("");
            TextTelefone.requestFocus();
            return;
        }
        
        //RESPONSÁVEL
        try {
            double teste;
            teste = Double.parseDouble(TextResponsavel.getText());
            JOptionPane.showMessageDialog(null, "NÃO É PERMITIDO NÚMEROS NO CAMPO RESPONSÁVEL");
            TextResponsavel.setText("");
            TextResponsavel.requestFocus();
            return;
        } catch (Exception responsavel) {
            
        }
        if (TextResponsavel.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "CAMPO RESPONSÁVEL NÃO PODE SER VAZIO");
            TextResponsavel.requestFocus();
            return;
        }
        
        try{
           if(TextID.getText().isEmpty()){ //REGISTRO NOVO
               dao.addFrigorifico(populateObjeto());
           }else{ //ATUALIZAÇÃO
               dao.updateFrigorifico(populateObjeto());
           }
           this.iniciaComponentes();
           this.carregaFrigorifico();
        }catch(Exception ex){
            System.out.println("ERRO: "+ex.getMessage());
        }
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void ButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRemoverActionPerformed
        // TODO add your handling code here:
        if (TextID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"DE UM DUPLO CLIQUE NO REGISTRO QUE DESEJA EXCLUIR");
            return;
        }
        if (JOptionPane.showConfirmDialog(null, "DESEJA EXCLUIR?")!=0){
            iniciaComponentes();
            return;
        }
        try{
            dao.deleteFrigorifico(populateObjeto());
            iniciaComponentes();
            carregaFrigorifico();
        }catch(Exception ex){
            System.out.println("ERRO: "+ex.getMessage());
        }
    }//GEN-LAST:event_ButtonRemoverActionPerformed

    private void ButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesquisarActionPerformed
        // TODO add your handling code here:
        if(TextPesquisar.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"DIGITE ALGO PARA PESQUISAR");
            TextPesquisar.requestFocus();
        } 
        try{
            this.carregaFrigorifico(TextPesquisar.getText());
           }catch(Exception ex){
            System.out.println("ERRO: "+ex.getMessage());
        }
    }//GEN-LAST:event_ButtonPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogFrigorifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogFrigorifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogFrigorifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogFrigorifico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogFrigorifico dialog = new DialogFrigorifico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonNovo;
    private javax.swing.JButton ButtonPesquisar;
    private javax.swing.JButton ButtonRemover;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JTable TableFrigorifico;
    private javax.swing.JFormattedTextField TextCNPJ;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextID;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextPesquisar;
    private javax.swing.JTextField TextResponsavel;
    private javax.swing.JFormattedTextField TextTelefone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
