/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.DaoCliente;
import Model.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author gusta
 */
public class DialogCliente extends javax.swing.JDialog {
    
    DaoCliente dao = new DaoCliente();
    
    //filtros
    private void carregaCliente(){
        TableCliente.setModel(new MyTableModel( Cliente.class, dao.getClienteList(), TableCliente));          
    }
    
    private void carregaCliente(String filtro){
        TableCliente.setModel(new MyTableModel( Cliente.class, dao.getClienteList(filtro), TableCliente));          
    }
        
    //INICIAR COMPONENTES
    private void iniciaComponentes(){
        TextID.setText("");
        TextNome.setText("");
        TextCNPJ.setText("");
        TextTelefone.setText("");
        TextEndereco.setText("");
        TextContato.setText("");
        TextPesquisar.setText("");
        TextNome.requestFocus();
    }
    //CRIAR UM OBJETO A PARTIR DA TELA
    private Cliente populateObjeto(){
        return(new Cliente(TextID.getText().isEmpty() ? 0 : Integer.parseInt(TextID.getText()),
                TextNome.getText(),
                TextCNPJ.getText(),
                TextTelefone.getText(),
                TextEndereco.getText(),
                TextContato.getText()));
    }
    //PREENCHER OS COMPONENTES COM UM OBJETO
    private void populateComponente(Cliente cliente){
        TextID.setText(cliente.getId()+""); //"" converte para string nesse caso
        TextNome.setText(cliente.getNome());
        TextCNPJ.setText(cliente.getCnpj());
        TextTelefone.setText(cliente.getTelefone());
        TextEndereco.setText(cliente.getEndereco());
        TextContato.setText(cliente.getContato());  
    }

    /**
     * Creates new form DialogCliente
     */
    public DialogCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TextID = new javax.swing.JTextField();
        TextNome = new javax.swing.JTextField();
        TextEndereco = new javax.swing.JTextField();
        TextContato = new javax.swing.JTextField();
        TextCNPJ = new javax.swing.JFormattedTextField();
        TextTelefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        TextPesquisar = new javax.swing.JTextField();
        ButtonPesquisar = new javax.swing.JButton();
        ButtonNovo = new javax.swing.JButton();
        ButtonSalvar = new javax.swing.JButton();
        ButtonRemover = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CLIENTE");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("CADASTRO"));

        jLabel1.setText("CÓDIGO");

        jLabel2.setText("NOME");

        jLabel3.setText("CNPJ");

        jLabel4.setText("TELEFONE");

        jLabel5.setText("ENDEREÇO");

        jLabel6.setText("NOME DO CONTATO");

        TextID.setEditable(false);

        try {
            TextCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TextTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) # ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("PESQUISAR CLIENTE OU CNPJ");

        ButtonPesquisar.setText("PESQUISAR");
        ButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPesquisarActionPerformed(evt);
            }
        });

        ButtonNovo.setText("NOVO");
        ButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNovoActionPerformed(evt);
            }
        });

        ButtonSalvar.setText("SALVAR");
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        ButtonRemover.setText("REMOVER");
        ButtonRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextID, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(TextContato))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextNome))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(168, 168, 168)
                        .addComponent(ButtonNovo)
                        .addGap(105, 105, 105)
                        .addComponent(ButtonSalvar)
                        .addGap(108, 108, 108)
                        .addComponent(ButtonRemover))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonPesquisar)))
                .addGap(371, 371, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(TextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TextTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TextEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(TextContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(TextPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonNovo)
                    .addComponent(ButtonSalvar)
                    .addComponent(ButtonRemover))
                .addGap(28, 28, 28))
        );

        TableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        // TODO add your handling code here:
        //NOME
        try {
            double teste;
            teste = Double.parseDouble(TextNome.getText());
            JOptionPane.showMessageDialog(null, "NÃO É PERMITIDO NÚMEROS NO CAMPO DE NOME");
            TextNome.setText("");
            TextNome.requestFocus();
            return;
        } catch (Exception nome) {
            
        }
        
        if (TextNome.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "CAMPO NOME NÃO PODE SER VAZIO");
            TextNome.requestFocus();
            return;
        }
        
        //CNPJ
        if(TextCNPJ.getText().equals("  .   .   /    -  ")){
            JOptionPane.showMessageDialog(null, "CAMPO CNPJ NÃO PODE SER VAZIO");
            TextCNPJ.setText("");
            TextCNPJ.requestFocus();
            return;
        }
        
        //TELEFONE
        if(TextTelefone.getText().equals("(  )       -    ")){
            JOptionPane.showMessageDialog(null, "CAMPO TELEFONE NÃO PODE SER VAZIO");
            TextTelefone.setText("");
            TextTelefone.requestFocus();
            return;
        }
        
        //ENDEREÇO
        if (TextEndereco.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "CAMPO ENDEREÇO NÃO PODE SER VAZIO");
            TextEndereco.requestFocus();
            return;
        }
        
        //CONTATO
        try {
            double teste;
            teste = Double.parseDouble(TextContato.getText());
            JOptionPane.showMessageDialog(null, "NÃO É PERMITIDO NÚMEROS NO CAMPO DE CONTATO");
            TextContato.setText("");
            TextContato.requestFocus();
            return;
        } catch (Exception nome_contato) {
            
        }
        
        if (TextContato.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "CAMPO CONTATO NÃO PODE SER VAZIO");
            TextContato.requestFocus();
            return;
        }
        
        
      try{
           if(TextID.getText().isEmpty()){ //REGISTRO NOVO
               dao.addCliente(populateObjeto());
           }else{ //ATUALIZAÇÃO
               dao.updateCliente(populateObjeto());
           }
           this.iniciaComponentes();
           this.carregaCliente();
        }catch(Exception ex){
            System.out.println("ERRO: "+ex.getMessage());
        }
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void ButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonNovoActionPerformed
        // TODO add your handling code here:
        this.iniciaComponentes();
    }//GEN-LAST:event_ButtonNovoActionPerformed

    private void ButtonRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRemoverActionPerformed
        // TODO add your handling code here:
        if (TextID.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"DE UM DUPLO CLIQUE NO REGISTRO QUE DESEJA EXCLUIR");
            return;
        }
        if (JOptionPane.showConfirmDialog(null, "DESEJA EXCLUIR?")!=0){
            iniciaComponentes();
            return;
        }
        try{
            dao.deleteCliente(populateObjeto());
            iniciaComponentes();
            carregaCliente();
        }catch(Exception ex){
            System.out.println("ERRO: "+ex.getMessage());
        }
    }//GEN-LAST:event_ButtonRemoverActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try{
            this.carregaCliente();
        }catch(Exception ex){
            System.out.println("ERRO: "+ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void ButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonPesquisarActionPerformed
        // TODO add your handling code here:
        if(TextPesquisar.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null,"DIGITE ALGO PARA PESQUISAR");
            TextPesquisar.requestFocus();
        } 
        this.carregaCliente(TextPesquisar.getText());
    }//GEN-LAST:event_ButtonPesquisarActionPerformed

    private void TableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableClienteMouseClicked
        // TODO add your handling code here:
        
            if (evt.getClickCount()==2){
                String valor= TableCliente.getValueAt(TableCliente.getSelectedRow(),0)+""; //+"" TRANSFORMA EM STRING
                int codigo = Integer.parseInt(valor);
                this.populateComponente(dao.getCliente(codigo));
            }
    }//GEN-LAST:event_TableClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCliente dialog = new DialogCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonNovo;
    private javax.swing.JButton ButtonPesquisar;
    private javax.swing.JButton ButtonRemover;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JTable TableCliente;
    private javax.swing.JFormattedTextField TextCNPJ;
    private javax.swing.JTextField TextContato;
    private javax.swing.JTextField TextEndereco;
    private javax.swing.JTextField TextID;
    private javax.swing.JTextField TextNome;
    private javax.swing.JTextField TextPesquisar;
    private javax.swing.JFormattedTextField TextTelefone;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
